package com.entitycheck.model;

public enum OrderStatus {
    ORDER_PLACED,
    PENDING_DATA_FETCH,
    DATA_FETCH_IN_PROGRESS,
    DATA_FETCHED,
    IN_PROGRESS,
    CREDIT_REPORT_GENERATION_IN_PROGRESS,
    CREDIT_REPORT_GENERATED,
    CREDIT_REPORT_GENERATION_FAILED,
    MODEL_EXECUTED,
    PDF_GENERATION_IN_PROGRESS,
    PDF_GENERATED,
    PDF_GENERATION_FAILED,
    COMPLETED,
    CANCELLED
}
